### ISSUE TITLE
Installation fails on Ubuntu 

### ISSUE THREAD

**Issue by flyingfrog81** [ska-telescope/ansible-playbooks#1]
On a freshly created Ubuntu bionic64. 
Base box used: https://app.vagrantup.com/ubuntu/boxes/bionic64 
See the attached ansible log
[ansible.log](https://github.com/ska-telescope/ansible-playbooks/files/2836457/ansible.log)

**Comment by flyingfrog81** [comment]
Maybe we could ship this together with a Vagrantfile

**Comment by Matteo04052017** [comment]
Looking at the log it appears that you dedicated not enough memory to the box. 
You can check line 5570-5576:
"virtual memory exhausted: Cannot allocate memory", 
        "make[5]: *** [attrgetsetprop.lo] Error 1", 
        "make[5]: *** Waiting for unfinished jobs....", 
        "make[4]: *** [all-recursive] Error 1", 
        "make[3]: *** [all-recursive] Error 1", 
        "make[2]: *** [all-recursive] Error 1", 
        "make[1]: *** [all-recursive] Error 1", 
        "make: *** [all] Error 2"

Try adding more RAM, like 4GB.

**Comment by flyingfrog81** [comment]
4GB RAM completes the installation!
